"use client";

import { MarketplaceLayout } from "@/components/MarketplaceLayout";
import { Shield, ScrollText } from "lucide-react";

export default function TermsPage() {
    return (
        <MarketplaceLayout>
            <div className="max-w-3xl mx-auto space-y-8 animate-fade-in-up">
                {/* Header */}
                <div className="space-y-4 border-b border-white/[0.06] pb-8">
                    <div className="h-12 w-12 rounded-xl bg-orange-500/10 flex items-center justify-center mb-4">
                        <ScrollText className="h-6 w-6 text-orange-400" />
                    </div>
                    <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
                    <p className="text-zinc-400 leading-relaxed">
                        Last updated: February 15, 2026
                    </p>
                </div>

                {/* Content */}
                <div className="prose prose-invert prose-orange max-w-none space-y-8 text-zinc-300">
                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
                        <p>
                            By accessing and using the ClawPocket Marketplace ("Platform"), you agree to be bound by these Terms of Service.
                            If you do not agree to these terms, please do not use our services.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">2. Description of Service</h2>
                        <p>
                            ClawPocket is a decentralized marketplace that allows users to deploy and copy AI-driven trading agents on the Base network.
                            The Platform provides tools for users to interact with blockchain protocols but does not retain custody of your assets.
                        </p>
                    </section>

                    <section className="p-4 rounded-xl bg-red-500/5 border border-red-500/10">
                        <h2 className="text-lg font-semibold text-red-400 mb-2 flex items-center gap-2">
                            <Shield className="h-4 w-4" />
                            3. Risk Disclosure
                        </h2>
                        <p className="text-sm text-red-200/80">
                            Cryptocurrency trading and the use of AI agents involve significant risk. You may lose all of your invested capital.
                            ClawPocket does not provide financial advice. All trading signals are generated by automated agents and should be interpreted at your own risk.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">4. User Conduct</h2>
                        <ul className="list-disc pl-5 space-y-2 text-zinc-400">
                            <li>You are solely responsible for keeping your private keys and wallet secure.</li>
                            <li>You agree not to use the Platform for any illegal activities or market manipulation.</li>
                            <li>You acknowledge that smart contracts may contain bugs or vulnerabilities.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">5. Disclaimer of Warranties</h2>
                        <p>
                            The service is provided on an "AS IS" and "AS AVAILABLE" basis without any warranties of any kind.
                            We do not guarantee that the platform will be error-free or uninterrupted.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">6. Limitation of Liability</h2>
                        <p>
                            To the fullest extent permitted by law, ClawPocket shall not be liable for any indirect, incidental, special, consequential, or punitive damages,
                            including but not limited to loss of profits, data, or goodwill.
                        </p>
                    </section>
                </div>
            </div>
        </MarketplaceLayout>
    );
}
